// generated by "sampctl package init"
#include <a_samp>
#include <formatex>

main() 
{
	new str[128];
	formatex(str, sizeof str, "My favourite vehicle is: '%v'!", 400); // shoul
	print(str);
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}
